### ISSUE TITLE
default appHost value does not change

### ISSUE THREAD

**Issue by Kwinnieprince** [kgritesh/gatsby-plugin-posthog-analytics#1]
I am hosting posthog myself so i do not use the defaut posthog domain.
when i change the appHost from ```https://app.posthog.com``` to ```https://my.domain.me``` it does not change.

**Comment by timgl** [comment]
I've created a PR to fix the typo in the readme, try using `apiHost` instead of `appHost`

**Comment by Kwinnieprince** [comment]
Thanks! I was also going to look into it but I didn't have the time today.
